### ISSUE TITLE
Allow templating in the iris.yaml

### ISSUE THREAD

**Issue by CKarper** [olegsu/iris#33]
Allowing token replacement, or some more powerful templating would allow for using Secrets to manage the `secret` for destinations.

**Comment by olegsu** [comment]
@CKarper I'm not sure I completely understand you, could you please give an example?
We can support references to environment variables, go templates (like helm does) or injection from other places

**Comment by CKarper** [comment]
Any of those options would work.

I was thinking of something like:

```yaml
    filters:
      - name: WarningLevel
        type: jsonpath
        path: $.type
        value: Warning

    destinations:
      - name: webhook
        url: https://webhook.site/90107aec-ef7c-47b8-87ea-7575d9c450e0
        secret: {{ $SECRET }}

    integrations:
      - name: HookAllWarnings
        destinations:
        - webhook
        filters:
        - WarningLevel
```

This allows the secret to be handled in a `Secret`, while the rest of the config can be put into a `ConfigMap`

If you wanted something more full featured then that's fine as well, but a simple env var would be sufficient for what I envision.
