### ISSUE TITLE
New Docker releases

### ISSUE THREAD

**Issue by CKarper** [olegsu/iris#39]
If you don't mind, please build new docker images tagged for the latest version.

**Comment by CKarper** [comment]
The changes you made have built new tags, but for some reason I had to move the `iris.yaml` to the root folder instead of in the `/iris/` folder.  Not sure if that was expected.

**Comment by olegsu** [comment]
It is unexpected, could you please give an example?

**Comment by CKarper** [comment]
The arrowed lines used to be `/iris/iris.yaml`, but that didn't work after the version change.

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iris
  namespace: default
  labels:
    app: iris
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
      - env:
        - name: IRIS_FILE
          value: /iris.yaml     <-------------------------------
        - name: IRIS_IN_CLUSTER
          value: "TRUE"
        name: iris
        command:
        - "iris"
        - "run"
        imagePullPolicy: IfNotPresent
        image: olsynt/iris:0.6.1
        volumeMounts:
        - name: config
          mountPath: /iris.yaml     <-------------------------------
          subPath: iris
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: iris
```
